### ISSUE TITLE
Missing several Meta files in repository

### ISSUE THREAD

**Issue by sobolevn** [samueljseay/recaptcha#16]
I guess the working process may be improved if we would provide two extra files for our potential contributors. I am talking about:

- [ ] changelog: so it would be clear what have changed
- [ ] contributing.md: so it would be clear how to contribute to the repo (how to run tests and style-checks)

What do you think?

**Comment by samueljseay** [comment]
a contributing.md sounds good, always good to help people get on board with the project.

I've been using the [github release functionality](https://github.com/samueljseay/recaptcha/releases) to document changes though, and I think thats better since its nicely formatted and has all the useful info. I think its imperative to ensure we keep these release notes as detailed as possible to make them useful though.

**Comment by samueljseay** [comment]
Closing this, since I haven't had any further feedback.
